### ISSUE TITLE
Publishing on Open VSX Registry (VS Code)

### ISSUE THREAD

**Issue by cravend** [zenclabs/previewjs#58]
**Is your feature request related to a problem? Please describe.**
I'm currently in the process of moving from the official build VS Code to [VSCodium](https://github.com/VSCodium/vscodium). However, it doesn't seem like the React Preview extension is published on the [Open VSX Registry](https://open-vsx.org) (the open-source version of the VS Code Marketplace). 

**Describe the solution you'd like**
Would it be possible for y'all to publish the extension on the public registry? Instructions are [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Describe alternatives you've considered**
The alternative is to directly download the `VSIX` and upload it manually, but that's not as fun as downloading from the marketplace.

**Additional context**
Looking forward to checking out React Preview!

**Comment by fwouts** [comment]
Hi @cravend and @lrkwz, I just went through the process of publishing to Open VSX Registry but I ended up stopping at the step of signing the Open VSX Publisher Agreement.

There is one particular clause (8.c) which as I understand it would expose me to significant financial risk if anyone decided to make a claim, founded or unfounded, against the extension. I know this is highly unlikely to happen in practice, but the liability in itself makes it a no-no for me 😞 
<img width="768" alt="Screen Shot 2022-01-31 at 5 04 10 pm" src="https://user-images.githubusercontent.com/772570/151746545-89095093-54e3-4de9-9d99-72a3f0b5176e.png">

You can still download the VSIX from the extension from the VS Code Marketplace to install it manually ("Download Extension" link): https://marketplace.visualstudio.com/items?itemName=zenclabs.previewjs

**Comment by lrkwz** [comment]
I'll go for the manual  install, no prbl. Thank you for your time spent building this useful util.

I've read the microsoft terms&agreement and (despite my bad english  ) it seems quite similar

![immagine](https://user-images.githubusercontent.com/1025560/151890245-5f468847-aa7d-448a-aceb-776d3980ee19.png)

**Comment by fwouts** [comment]
Yep, you're right. I must have missed that last year. I guess there's no avoiding it! I'll sign this one too then :)

**Comment by fwouts** [comment]
The extension is now published on https://open-vsx.org/extension/zenclabs/previewjs. It should auto-publish in the future with https://github.com/zenclabs/previewjs/commit/b7d4318678ed9476d78a5d5026671f10a3d6586f, but I haven't tested this process yet. We'll see with the next release!

You'll see a warning about ownership until https://github.com/EclipseFdn/open-vsx.org/issues/861 is solved.

Let me know if you run into any issues!
