### ISSUE TITLE
Not compatible with the latest WebStorm 2021.3

### ISSUE THREAD

**Issue by arkadiuszbachorski** [zenclabs/previewjs#68]
### Describe the bug

Latest WebStorm 2021.3 is not supported. Unable to install the plugin.

### Reproduction

1. Get WebStorm 2021.3
2. Go to https://plugins.jetbrains.com/plugin/17569-react-preview-beta-

### React Preview version

n/a

### System Info

```shell
n/a
```

### Used Package Manager

yarn

### Anything else?

![image](https://user-images.githubusercontent.com/60391032/147930515-fc1be868-ce04-4bdd-9f08-a9b8af5c5798.png)

**Comment by fwouts** [comment]
Hi @arkadiuszbachorski, I've just released v0.7.1, which should appear in the JetBrains store once they've approved it :) Thanks for reminding me and let me know how you go!

**Comment by arkadiuszbachorski** [comment]
Tried the plugin and it looks promising! I prefer Storybook for larger projects with couple devs, but I'll definitely try it out while developing things alone. 

I think we can close the ticket, thanks!
